# Generated by Django 4.2 on 2026-04-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumemodel",
            name="cleaned_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="resumemodel",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
    ]
