# Generated by Django 4.2 on 2026-04-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_resumemodel_cleaned_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumemodel",
            name="skills",
            field=models.JSONField(default=list),
        ),
    ]
